let x = 20;
console.log(x)
try{
    console.log(z)
}catch(err){
    console.log(err)
}